const chatData = {
  totalpeople: [
    { Name: "Alice", GoogleID: "alice@gmail.com" },
    { Name: "Bob", GoogleID: "bob@gmail.com" },
    { Name: "Charlie", GoogleID: "charlie@gmail.com" },
    { Name: "David", GoogleID: "david@gmail.com" },
    { Name: "Eve", GoogleID: "eve@gmail.com" },
    { Name: "Frank", GoogleID: "frank@gmail.com" },
    { Name: "Grace", GoogleID: "grace@gmail.com" },
    { Name: "Hannah", GoogleID: "hannah@gmail.com" },
    { Name: "Isaac", GoogleID: "isaac@gmail.com" },
    { Name: "Jack", GoogleID: "jack@gmail.com" },
    { Name: "Karen", GoogleID: "karen@gmail.com" },
    { Name: "Leo", GoogleID: "leo@gmail.com" },
    { Name: "Mia", GoogleID: "mia@gmail.com" },
    { Name: "Nina", GoogleID: "nina@gmail.com" },
    { Name: "Oscar", GoogleID: "oscar@gmail.com" },
    { Name: "Pam", GoogleID: "pam@gmail.com" },
    { Name: "Quinn", GoogleID: "quinn@gmail.com" }
  ],
  messages: [
    { from: "alice@gmail.com", to: "rohan@gmail.com", text: "Hey Rohan!", timestamp: "2025-04-18T10:00:00.000Z", read: false, delivered: false },
    { from: "bob@gmail.com", to: "rohan@gmail.com", text: "Morning, ready for the meeting?", timestamp: "2025-04-18T10:10:00.000Z", read: true, delivered: true },
    { from: "rohan@gmail.com", to: "charlie@gmail.com", text: "Can you check the code?", timestamp: "2025-04-18T10:20:00.000Z", read: true, delivered: true },
    { from: "david@gmail.com", to: "rohan@gmail.com", text: "Let’s catch up later.", timestamp: "2025-04-18T10:25:00.000Z", read: false, delivered: false },
    { from: "rohan@gmail.com", to: "eve@gmail.com", text: "Thanks for the notes!", timestamp: "2025-04-18T10:30:00.000Z", read: false, delivered: true },
    { from: "frank@gmail.com", to: "rohan@gmail.com", text: "When’s the deadline?", timestamp: "2025-04-18T10:35:00.000Z", read: false, delivered: false },
    { from: "rohan@gmail.com", to: "grace@gmail.com", text: "All good with the task?", timestamp: "2025-04-18T10:40:00.000Z", read: false, delivered: true },
    { from: "hannah@gmail.com", to: "rohan@gmail.com", text: "Let’s have a quick call.", timestamp: "2025-04-18T10:45:00.000Z", read: false, delivered: false },
    { from: "rohan@gmail.com", to: "isaac@gmail.com", text: "Need your review.", timestamp: "2025-04-18T10:50:00.000Z", read: true, delivered: true },
    { from: "jack@gmail.com", to: "rohan@gmail.com", text: "Lunch?", timestamp: "2025-04-18T10:55:00.000Z", read: false, delivered: false },
    { from: "rohan@gmail.com", to: "karen@gmail.com", text: "Check your inbox.", timestamp: "2025-04-18T11:00:00.000Z", read: true, delivered: true },
    { from: "leo@gmail.com", to: "rohan@gmail.com", text: "Where's the doc?", timestamp: "2025-04-18T11:05:00.000Z", read: false, delivered: false },
    { from: "mia@gmail.com", to: "rohan@gmail.com", text: "Got your message.", timestamp: "2025-04-18T11:10:00.000Z", read: true, delivered: true },
    { from: "rohan@gmail.com", to: "nina@gmail.com", text: "We’re on track.", timestamp: "2025-04-18T11:15:00.000Z", read: true, delivered: true },
    { from: "oscar@gmail.com", to: "rohan@gmail.com", text: "Any updates?", timestamp: "2025-04-18T11:20:00.000Z", read: false, delivered: false },
    { from: "pam@gmail.com", to: "rohan@gmail.com", text: "Need your confirmation.", timestamp: "2025-04-18T11:25:00.000Z", read: false, delivered: false },
    { from: "rohan@gmail.com", to: "quinn@gmail.com", text: "It’s done.", timestamp: "2025-04-18T11:30:00.000Z", read: true, delivered: true },
    { from: "alice@gmail.com", to: "rohan@gmail.com", text: "You coming today?", timestamp: "2025-04-18T11:35:00.000Z", read: false, delivered: false },
    { from: "bob@gmail.com", to: "rohan@gmail.com", text: "Send me the link.", timestamp: "2025-04-18T11:40:00.000Z", read: true, delivered: true },
    { from: "charlie@gmail.com", to: "rohan@gmail.com", text: "Looks great!", timestamp: "2025-04-18T11:45:00.000Z", read: false, delivered: false },
    { from: "david@gmail.com", to: "rohan@gmail.com", text: "Let’s reschedule.", timestamp: "2025-04-19T11:50:00.000Z", read: false, delivered: false },
    { from: "eve@gmail.com", to: "rohan@gmail.com", text: "Sure, got it!", timestamp: "2025-04-18T11:55:00.000Z", read: true, delivered: true },
    { from: "frank@gmail.com", to: "rohan@gmail.com", text: "Sending now.", timestamp: "2025-04-18T12:00:00.000Z", read: false, delivered: false },
    { from: "grace@gmail.com", to: "rohan@gmail.com", text: "You're doing great!", timestamp: "2025-04-18T12:05:00.000Z", read: false, delivered: false },
    { from: "hannah@gmail.com", to: "rohan@gmail.com", text: "Almost done!", timestamp: "2025-04-18T12:10:00.000Z", read: false, delivered: false },
    { from: "isaac@gmail.com", to: "rohan@gmail.com", text: "On it.", timestamp: "2025-04-18T12:15:00.000Z", read: true, delivered: true },
    { from: "jack@gmail.com", to: "rohan@gmail.com", text: "Meeting postponed.", timestamp: "2025-04-18T12:20:00.000Z", read: false, delivered: false },
    { from: "karen@gmail.com", to: "rohan@gmail.com", text: "Confirmed.", timestamp: "2025-04-18T12:25:00.000Z", read: true, delivered: true },
    { from: "leo@gmail.com", to: "rohan@gmail.com", text: "Thanks!", timestamp: "2025-04-18T12:30:00.000Z", read: true, delivered: true },
    { from: "mia@gmail.com", to: "rohan@gmail.com", text: "Ready when you are.", timestamp: "2025-04-18T12:35:00.000Z", read: false, delivered: false }
  ],
  online: [
    { Name: "David", GoogleID: "david@gmail.com" },
    { Name: "Eve", GoogleID: "eve@gmail.com" },
    { Name: "Frank", GoogleID: "frank@gmail.com" },
    { Name: "Grace", GoogleID: "grace@gmail.com" },
    { Name: "Hannah", GoogleID: "hannah@gmail.com" },
    { Name: "Isaac", GoogleID: "isaac@gmail.com" },
    { Name: "Jack", GoogleID: "jack@gmail.com" },
    { Name: "Karen", GoogleID: "karen@gmail.com" },
    { Name: "Leo", GoogleID: "leo@gmail.com" },
    { Name: "Mia", GoogleID: "mia@gmail.com" },
    { Name: "Nina", GoogleID: "nina@gmail.com" }
  ]
};

export default chatData;
