import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from "@/components/SessionWrapper";
import { ReduxProvider } from "./store/ReduxProvider";
import { ThemeProvider } from "next-themes";
import TokenManager from "@/components/tokenmanager";


export const metadata = {
  title: "Udan Chat-Ola",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="font-ubuntu" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <SessionWrapper> <TokenManager/>{children}</SessionWrapper>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
