import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import { SessionWrapper } from "@/components/SessionWrapper";
import { ReduxProvider } from "./store/ReduxProvider";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "Udan Chat-Ola",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ubuntu.className} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <SessionWrapper>{children}</SessionWrapper>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
